# .golangci.yml
version: "2"

run:
  # Optional: adjust as needed
  timeout: 5m
  go: "1.24.3"

formatters:
  enable:
    - goimports
    - gofmt

linters:
  enable:
    - gosec
    - govet
    - errcheck
    - staticcheck
    - gocritic
    - gocyclo
    - goconst
    - misspell
    # - revive TODO: Uncomment this and update the documentations
    - unconvert
    - ineffassign
    - dupl

  settings:
    gosec:
      config:
        global:
          nosec: true
      # By default, gosec uses its own rule set. You can customize here if needed.
      # exclude-use-default: false
      # include:
      #   - G104
      # exclude:
      #   - G101

output:
  show-stats: false
